name: WakaTime status update

on:
  schedule:
    - cron: "0 0 * * *" # Se actualiza cada noche
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # Esta es la acción que SÍ existe y funciona
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: 📋
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
