name: WakaTime Readme Stats
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: anuraghazra/github-readme-stats@v1
      with:
        api_key: ${{ secrets.WAKATIME_API_KEY }}
        username: ${{ secrets.GITHUB_USERNAME }}
